services:
  backend:
    build: ./backend
    container_name: ocr_tpv_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: ocr_tpv_frontend
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend